
# type Showing Data type


if True:  
    print("Python")
    print("Programming")

print(type(100))
print(type(100.1))

name = "Hello"
myName = "Hello"
my_name = "Hello"


print(name)
print(myName)
print(my_name)

x = 10
x = "Welcome"
print(x)

help("keywords") #Resrved Words

L, M, N= 1, 2 ,3
print(L,M,N)

#009

# Back Space
print("hello\bWorld")


#Escpe New Line +\
print("Hello \
    I Love \
    Python")


print(" Back Slach\"")
print(" Back Slach\\")
print('Back Slach \"test"')

#Line Feed
print("Hello World\nSecondline")

#Carriage Return
print("Hello World\rSecondline")
print("123456\rABCD")

#Horizontal Tab
print("Hello\t World")

#xhh Character Hex Value (Searche in goolgle letter hex value)
print("\x4F\x73")

